# Generated by Django 5.0.4 on 2024-11-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_userprofile_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
