# Generated by Django 5.0.4 on 2024-11-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_userprofile_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('fisioterapeuta', 'Fisioterapeuta')], default='paciente', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
