# Generated by Django 5.0.4 on 2024-11-24 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('fisioterapeuta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='usuarios.fisioterapeuta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='usuarios.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.fisioterapeuta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(fields=('fisioterapeuta', 'data', 'hora'), name='unique_fisioterapeuta_horario'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidade',
            unique_together={('fisioterapeuta', 'dia_semana', 'horario_inicio')},
        ),
    ]
