# Generated by Django 5.0.4 on 2024-11-22 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='fisioterapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='usuarios.user'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='usuarios.user'),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='fisioterapeuta',
            field=models.ForeignKey(limit_choices_to={'tipo': 'Fisioterapeuta'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.user'),
        ),
        migrations.AddField(
            model_name='fisioterapist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='usuarios.user'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(fields=('fisioterapeuta', 'data', 'hora'), name='unique_fisioterapeuta_horario'),
        ),
    ]
