# Generated by Django 5.0.4 on 2024-11-25 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='fisioterapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='agendamentos.fisioterapist'),
        ),
    ]
