# Generated by Django 5.0.4 on 2024-11-21 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_agendamento_options_and_more'),
        ('usuarios', '0004_userprofile_tipo_alter_userprofile_cpf_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='disponibilidade',
            name='fisioterapeuta',
            field=models.ForeignKey(limit_choices_to={'tipo': 'Fisioterapeuta'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(fields=('fisioterapeuta', 'data', 'hora'), name='unique_fisioterapeuta_horario'),
        ),
    ]
